version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app/main.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "8501:8501"
    depends_on:
      - postgres_db
      - mysql_db
    env_file:
      - .env
    networks:
      - my_network 

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_table_mysql.sql:/docker-entrypoint-initdb.d/init_table_mysql.sql
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  postgres_data:
  mysql_data:

networks:
  my_network:
    driver: bridge